# Generated by Django 4.0.5 on 2022-06-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('Students', 'Students'), ('Kids', 'Kids')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='flyer',
            field=models.ImageField(blank=True, null=True, upload_to='flyers'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('Seasonal', 'Seasonal'), ('Single', 'Single'), ('Test_ADD', 'Test_ADD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('ALL', 'ALL'), ('Students', 'Students'), ('Kids', 'Kids')], max_length=10),
        ),
    ]
